
url: https://lasica.co
title: kubalasecki
email: kuba@lasica.co
description: > # "Bla Bla Bla"

markdown: kramdown
permalink: pretty

skype_id: SkypeButton_Chat_kubica1988
skype_title: skype

social:
  - title: github
    url: https://github.com/kubalasecki
    id: githublink
  - title: linkedin
    url: https://pl.linkedin.com/in/kubalasecki
    id: linkedinlink
