
url: http://lasica.co
title: kubalasecki
email: kubalasecki@gmail.com
description: > # "Bla Bla Bla"

markdown: kramdown
permalink: pretty

social:
  - title: skype
    url: kubica1988
  - title: github
    url: https://github.com/kubalasecki
  - title: linkedin
    url: https://pl.linkedin.com/in/kubalasecki
